[build-system]
requires = ["setuptools>=45", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "phone-query-tool"
version = "0.1.0"
description = "手机号归属地批量查询工具"
authors = [
    {name = "kenneth", email = "kennethfan137@gmail.com"}
]
readme = "README.md"
license = {text = "Apache 2.0"}
requires-python = ">=3.8"
dependencies = [
    "requests>=2.25.0",
    "beautifulsoup4>=4.9.0",
    "lxml>=4.6.0"
]

[project.scripts]
phone-query-tool = "src.gui:main"

[tool.setuptools.packages.find]
where = ["src"]